spring:
  application:
    name: fund-advice-service
  datasource:
    url: jdbc:h2:mem:funds;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    user:
      name: admin
      password: admin123

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    com.myfund.advice: DEBUG

# GPT-5 Think 接入参数，通过环境变量或配置中心进行覆盖
gpt5think:
  api:
    base-url: https://api.your-gpt5-proxy.example.com
    key: TODO_FILL_GPT5_API_KEY
    model: gpt-5-think
